---
apiVersion: v2
description: Kub application template for deploy to k8s
home: https://github.com/sham1316/kub-app
maintainers:
- email: sham1316@gmail.com
  name: sham
name: kub-lib

# Don`t edit version. Use git tag to publish your release
version: 01.01.01

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: library
