{{- $root := . -}}
{{- range $cjName, $cj := $root.Values.cronjobs }}
{{- if $cj.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kub-app.fullname" $root }}-{{ $cjName }}
  labels:
    {{- include "kub-app.labels" $root | nindent 4 }}
  annotations:
    checksum/config: {{ $cj.containers | toJson | sha256sum }}
spec:
  schedule: {{ $cj.schedule | quote }}
  concurrencyPolicy: {{ $cj.concurrencyPolicy | default "Forbid" }}
  successfulJobsHistoryLimit: {{ $cj.successfulJobsHistoryLimit | default 1 }}
  jobTemplate:
    metadata:
      labels:
        {{- include "kub-app.labels" $root | nindent 8 }}
        app_type: "Job"
      annotations:
        checksum/config: {{ $cj.containers | toJson | sha256sum }}
    spec:
      {{- if $cj.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ $cj.activeDeadlineSeconds }}
      {{- end }}
      ttlSecondsAfterFinished: {{ $cj.ttlSecondsAfterFinished | default 7200 }}
      template:
        metadata:
          labels:
            {{- include "kub-app.labels" $root | nindent 12 }}
          annotations:
            checksum/config: {{ $cj.containers | toJson | sha256sum }}
        spec:
          restartPolicy: OnFailure
          containers:
          {{- range $name, $container := $cj.containers }}
            - name: {{ $name }}
              image: {{ $container.image }}
              {{- if $container.command }}
              command:
                {{- $container.command | toYaml | nindent 16 }}
              {{- end }}
              {{- if $container.args }}
              args:
                - {{ $container.args | quote }}
              {{- end }}
              env:
                {{- include "kub-app-lib.env" $root | nindent 16 }}
                {{- include "kub-app-lib.env.secrets" $root | nindent 16 }}
          {{- end }}
{{- end }}
{{- end }}