{{- if .Values.deployments.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kub-app.fullname" . }}
  labels:
    {{- include "kub-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if or .Values.strategy }}
  strategy:
  {{ toYaml .Values.strategy | indent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kub-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kub-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kub-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "kub-app-lib.env" $ | nindent 12 }}
            {{- include "kub-app-lib.env.secrets" $ | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.monitoring.enabled }}
            - name: monitoring
              containerPort: {{ .Values.monitoring.port }}
              protocol: TCP
            {{- end }}
         {{- if or .Values.volumes .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.path }}
              name: storage-volume
         {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.deployments.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.deployments.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 14 }}
          {{- end }}
          {{- with .Values.deployments.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 14 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.volumes .Values.persistence.enabled }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "kub-app.fullname" .) }}
      {{- end }}
      {{- end }}
  {{- end -}}