{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "kub-app.fullname" . }}
  labels:
    {{- include "kub-app.labels" . | nindent 4 }}
  {{- with .Values.monitoring.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - port: monitoring
      {{- if .Values.monitoring.podMonitor.interval }}
      interval: {{ .Values.monitoring.podMonitor.interval }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.monitoring.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.honorLabels }}
      honorLabels: {{ .Values.monitoring.podMonitor.honorLabels }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.relabelings }}
      relabelings: {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.metricRelabelings }}
      metricRelabelings: {{- toYaml .Values.monitoring.podMonitor.metricRelabelings | nindent 6 }}
      {{- end }}
      {{- if .Values.monitoring.podMonitor.path }}
      path: {{ .Values.monitoring.podMonitor.path }}
      {{- end }}
      {{- range .Values.monitoring.podMonitor.additionalEndpoints }}
    - port: {{ .port }}
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
      {{- if .scrapeTimeout }}
      scrapeTimeout: {{ .scrapeTimeout }}
      {{- end }}
      {{- if .honorLabels }}
      honorLabels: {{ .honorLabels }}
      {{- end }}
      {{- with concat $.Values.monitoring.serviceMonitor.relabelings $.Values.monitoring.serviceMonitor.relabellings }}
      relabelings: {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .metricRelabelings }}
      metricRelabelings: {{- toYaml .metricRelabelings | nindent 6 }}
      {{- end }}
      {{- if .path }}
      path: {{ .path }}
      {{- end }}
      {{- if .params }}
      params:
        {{- range $key, $value := .params }}
        {{ $key }}:
          {{- range $value }}
        - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.monitoring.podMonitor.podTargetLabels }}
  podTargetLabels: {{- toYaml .Values.monitoring.podMonitor.podTargetLabels | nindent 4 }}
  {{- end }}
  {{- with .Values.monitoring.podMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .Values.monitoring.podMonitor.targetLimit }}
  targetLimit: {{ . }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels: {{- include "kub-app.labels" . | nindent 6 }}
{{- end }}