---
# Source: kub-app/templates/Secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app1
  namespace: testns
  labels:
    helm.sh/chart: kub-app-01.01.01
    app.kubernetes.io/version: "01.01.01"
    app.kubernetes.io/name: app1
    app.kubernetes.io/instance: app1
    app.kubernetes.io/managed-by: Helm
  annotations:
    app.kubernetes.io/version: "01.01.01"
    helm.sh/chart: kub-app-01.01.01    
    helm.sh/hook: "pre-upgrade"
stringData:
  topSecret: "42"
