replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imageCredentials: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
  imagePullSecrets: []

deployments:
  enabled: true
  startupProbe: {}
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

monitoring:
  enabled: false
  port: 8082
  exp: health,info,prometheus,metrics

podAnnotations: {}
podLabels: {}

configMap: []
postgresExternalSecretName: externalSecretName
externalSecretName: externalSecretName
hazelcastEnv:
  - HAZELCAST_CLUSTER_NAME
  - HAZELCAST_LABEL_NAME
  - HAZELCAST_LABEL_VALUE
  - HAZELCAST_NAME
  - HAZELCAST_NAMESPACE
  - HAZELCAST_URL

env: []
secretEnv: []
#
#env:
#  APP: TEST

podSecurityContext: {}

securityContext: {}

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  custombehaviour:
    enabled: false
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  enabled: false
